inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

Style/StringLiterals:
  Enabled: true
  #  EnforcedStyle: double_quotes
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  #  EnforcedStyle: double_quotes
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

#追加
Style/FrozenStringLiteralComment:
  Enabled: false
#
Style/StringConcatenation:
  Enabled: false
#
Naming/AccessorMethodName:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
#
RSpec/SpecFilePathFormat:
  Enabled: true
RSpec/SpecFilePathSuffix:
  Enabled: true
#
RSpec/FilePath:
  Enabled: false
